### PR TITLE
Fixes issue #1 where a single user-supplied ConfigSource was not being incorporated

### LINKED ISSUE #1: Unable to construct a `Config` with just a single `ConfigSource`, no default/discovered.
This fails to add any config sources to the constructed `Config` because of [this](https://github.com/microbean/microbean-microprofile-config/blob/master/src/main/java/org/microbean/microprofile/config/ConfigBuilder.java#L105) (i.e. sources is null when we choose not to add default or discovered config sources).

```java
ConfigProviderResolver.instance()
                .getBuilder()
                .withSources(new MyCustomSource())
                .build()
```

### PR DESCRIPTION
**Pull request by ljnelson**
Signed-off-by: Laird Nelson <ljnelson@gmail.com>

### CODE REVIEW

File: src/main/java/org/microbean/microprofile/config/ConfigBuilder.java [hunk 1]
```diff
@@ -93,30 +93,31 @@ public final Config build() {
...
     }
-    
-    if (sources != null) {
-      synchronized (this.sources) {
-        sources.addAll(this.sources);
-        Collections.sort(sources, ConfigSourceComparator.INSTANCE);
-      }
+
+    if (sources == null) {
+      sources = new LinkedList<>();
```
Comment (jkschneider) [inline src/main/java/org/microbean/microprofile/config/ConfigBuilder.java]: This means that no matter what, `sources` will always have a non-null value by the end of this method. It might be simpler then to just initialize it to a `LinkedList` in the first place and avoid all these null checks.

Comment (jkschneider) [reply src/main/java/org/microbean/microprofile/config/ConfigBuilder.java]: Perhaps also reserve sorting for the end then as well after all discovered, default, and user-supplied sources are in the list. If the list is empty, sorting should be instant.
